<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R5"><DocLocation><![CDATA[C:\Banking\Automation\TestScripts\Testcase99_EXP_09_79]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Testcase99_EXP_09_79]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="256" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:16]]></Time>
<TimeTick>1632153676</TimeTick>
<NodeArgs eType="Replay" icon="259" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:16]]></Time>
<TimeTick>1632153676</TimeTick>
<NodeArgs eType="Replay" icon="259" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:19]]></Time>
<TimeTick>1632153679</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:19]]></Time>
<TimeTick>1632153679</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="12" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:21]]></Time>
<TimeTick>1632153681</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="14" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:21]]></Time>
<TimeTick>1632153681</TimeTick>
<NodeArgs eType="Replay" icon="262" nRep="16" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:21]]></Time>
<TimeTick>1632153681</TimeTick>
<NodeArgs eType="Replay" icon="262" nRep="18" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fc097abb195b0915582818a640b"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:21]]></Time>
<TimeTick>1632153681</TimeTick>
<NodeArgs eType="Replay" icon="262" nRep="20" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:21]]></Time>
<TimeTick>1632153681</TimeTick>
<NodeArgs eType="Replay" icon="262" nRep="22" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:26]]></Time>
<TimeTick>1632153686</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="24" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:28]]></Time>
<TimeTick>1632153688</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="25" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:28]]></Time>
<TimeTick>1632153688</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="27" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:31]]></Time>
<TimeTick>1632153691</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="28" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:31]]></Time>
<TimeTick>1632153691</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="30" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#6"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:32]]></Time>
<TimeTick>1632153692</TimeTick>
<NodeArgs eType="Replay" icon="263" nRep="32" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:34]]></Time>
<TimeTick>1632153694</TimeTick>
<NodeArgs eType="Replay" icon="263" nRep="34" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Manual Declare.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:44]]></Time>
<TimeTick>1632153704</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="36" >
<Disp><![CDATA[Manual Declare.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:52]]></Time>
<TimeTick>1632153712</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="38" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Declare Till / Mid-Day.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["CASH"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:54]]></Time>
<TimeTick>1632153714</TimeTick>
<NodeArgs eType="Replay" icon="263" nRep="40" >
<Disp><![CDATA[Declare Till / Mid-Day.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Enter Expected Quantity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["20.34"]]></Details>
<Time><![CDATA[9/20/2021 - 17:01:58]]></Time>
<TimeTick>1632153718</TimeTick>
<NodeArgs eType="Replay" icon="262" nRep="42" >
<Disp><![CDATA[Enter Expected Quantity.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Count Complete.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:02:02]]></Time>
<TimeTick>1632153722</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="44" >
<Disp><![CDATA[Count Complete.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[PIS Confirmation.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["919316"]]></Details>
<Time><![CDATA[9/20/2021 - 17:02:06]]></Time>
<TimeTick>1632153726</TimeTick>
<NodeArgs eType="Replay" icon="262" nRep="46" >
<Disp><![CDATA[PIS Confirmation.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 17:02:11]]></Time>
<TimeTick>1632153731</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="47" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:02:11]]></Time>
<TimeTick>1632153731</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="49" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="260" nRep="11" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Banking]]></Obj>
<Details ><![CDATA[Confirmation screen is displayed Successfully]]></Details>
<Time><![CDATA[9/20/2021 - 17:02:11]]></Time>
<TimeTick>1632153731</TimeTick>
<NodeArgs eType="User" icon="264" nRep="50" status="Passed" >
<Disp><![CDATA[Banking]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:47]]></Time>
<TimeTick>1632153827</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Save Print Output As]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:47]]></Time>
<TimeTick>1632153827</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Cancel.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:47]]></Time>
<TimeTick>1632153827</TimeTick>
<NodeArgs eType="Replay" icon="267" nRep="57" >
<Disp><![CDATA[Cancel.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="266" nRep="56" >
<Disp><![CDATA[Save Print Output As]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="265" nRep="55" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:49]]></Time>
<TimeTick>1632153829</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#7"]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:49]]></Time>
<TimeTick>1632153829</TimeTick>
<NodeArgs eType="Replay" icon="263" nRep="60" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:51]]></Time>
<TimeTick>1632153831</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="62" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:51]]></Time>
<TimeTick>1632153831</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="63" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:51]]></Time>
<TimeTick>1632153831</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="65" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Count Complete.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:03:55]]></Time>
<TimeTick>1632153835</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="67" >
<Disp><![CDATA[Count Complete.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:05]]></Time>
<TimeTick>1632153845</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="69" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="260" nRep="59" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:09]]></Time>
<TimeTick>1632153849</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Save Print Output As.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:09]]></Time>
<TimeTick>1632153849</TimeTick>
<NodeArgs eType="Replay" icon="266" nRep="72" >
<Disp><![CDATA[Save Print Output As.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="265" nRep="71" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:11]]></Time>
<TimeTick>1632153851</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:11]]></Time>
<TimeTick>1632153851</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="75" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:16]]></Time>
<TimeTick>1632153856</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="77" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:18]]></Time>
<TimeTick>1632153858</TimeTick>
<NodeArgs eType="Replay" icon="261" nRep="79" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Back Office Login(st).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:18]]></Time>
<TimeTick>1632153858</TimeTick>
<NodeArgs eType="Replay" icon="268" nRep="80" >
<Disp><![CDATA[Back Office Login(st).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="260" nRep="74" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Successfully logged out]]></Obj>
<Details ><![CDATA[Logged out successfully]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:18]]></Time>
<TimeTick>1632153858</TimeTick>
<NodeArgs eType="User" icon="264" nRep="81" status="Passed" >
<Disp><![CDATA[Successfully logged out]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/20/2021 - 17:04:18]]></Time>
<TimeTick>1632153858</TimeTick>
<NodeArgs eType="General" icon="269" nRep="82" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/20/2021 - 17:01:13" eTime="9/20/2021 - 17:04:18" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="258" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="257" nRep="6" status="Passed" >
<Disp><![CDATA[Testcase99_EXP_09_79 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/20/2021 - 17:01:11" eTime="9/20/2021 - 17:04:18" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="255" nRep="3" status="Passed" >
<Disp><![CDATA[Test Testcase99_EXP_09_79 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>