<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R5"><DocLocation><![CDATA[C:\Banking\Automation\TestScripts\Testcase108_EXP_09_57]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Testcase108_EXP_09_57]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="374" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:11]]></Time>
<TimeTick>1632144431</TimeTick>
<NodeArgs eType="Replay" icon="377" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:11]]></Time>
<TimeTick>1632144431</TimeTick>
<NodeArgs eType="Replay" icon="377" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:13]]></Time>
<TimeTick>1632144433</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:13]]></Time>
<TimeTick>1632144433</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="11" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log Off.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:33]]></Time>
<TimeTick>1632144453</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="13" status="Warning" >
<Disp><![CDATA[Log Off.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Log Off]]></Obj>
<Details plainTxt="False" ><![CDATA[Object&nbsp;is&nbsp;disabled]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:33]]></Time>
<TimeTick>1632144453</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Log Off]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaButton<br>Label = Log Off<br>]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:33]]></Time>
<TimeTick>1632144453</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="16" status="Warning" nType="Description" >
<Disp><![CDATA[Log Off]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="379" nRep="15" status="Failed" nType="Run Error" >
<Disp><![CDATA[Log Off]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="10" status="Failed" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:33]]></Time>
<TimeTick>1632144453</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (11): &quot;		JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaButton(&quot;Log Off&quot;).Click&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:33]]></Time>
<TimeTick>1632144453</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="18" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="10" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Till.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:36]]></Time>
<TimeTick>1632144456</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="20" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Till.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="17" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:58]]></Time>
<TimeTick>1632144478</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[General run error.<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (72): &quot;			JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Login&quot;).Highlight&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:27:58]]></Time>
<TimeTick>1632144478</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="23" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="71" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:19]]></Time>
<TimeTick>1632144499</TimeTick>
<NodeArgs eType="Replay" icon="381" nRep="26" status="Warning" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Login"&nbsp;(of&nbsp;class&nbsp;JavaEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:19]]></Time>
<TimeTick>1632144499</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaEdit<br>Attached Text = Login<br>]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:19]]></Time>
<TimeTick>1632144499</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="29" status="Warning" nType="Description" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="381" nRep="28" status="Failed" nType="Run Error" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="22" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:19]]></Time>
<TimeTick>1632144499</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Login&quot; (of class JavaEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (73): &quot;			JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Login&quot;).Set strUsername&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:19]]></Time>
<TimeTick>1632144499</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="31" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="72" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:39]]></Time>
<TimeTick>1632144519</TimeTick>
<NodeArgs eType="Replay" icon="381" nRep="34" status="Warning" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Login"&nbsp;(of&nbsp;class&nbsp;JavaEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:39]]></Time>
<TimeTick>1632144519</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaEdit<br>Attached Text = Login<br>]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:39]]></Time>
<TimeTick>1632144519</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="37" status="Warning" nType="Description" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="381" nRep="36" status="Failed" nType="Run Error" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="30" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:39]]></Time>
<TimeTick>1632144519</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Login&quot; (of class JavaEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (74): &quot;			JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Login&quot;).Activate&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:28:39]]></Time>
<TimeTick>1632144519</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="39" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="73" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="38" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:00]]></Time>
<TimeTick>1632144540</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[General run error.<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (75): &quot;			JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Login&quot;).Highlight&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:00]]></Time>
<TimeTick>1632144540</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="42" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="74" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fc097abb195b0915582818a640b"]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:21]]></Time>
<TimeTick>1632144561</TimeTick>
<NodeArgs eType="Replay" icon="381" nRep="45" status="Warning" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Login"&nbsp;(of&nbsp;class&nbsp;JavaEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:21]]></Time>
<TimeTick>1632144561</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaEdit<br>Attached Text = Login<br>]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:21]]></Time>
<TimeTick>1632144561</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="48" status="Warning" nType="Description" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="381" nRep="47" status="Failed" nType="Run Error" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="41" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:21]]></Time>
<TimeTick>1632144561</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Login&quot; (of class JavaEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (76): &quot;			JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Login&quot;).SetSecure strPassword&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:21]]></Time>
<TimeTick>1632144561</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="50" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="75" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:41]]></Time>
<TimeTick>1632144581</TimeTick>
<NodeArgs eType="Replay" icon="381" nRep="53" status="Warning" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Login"&nbsp;(of&nbsp;class&nbsp;JavaEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:41]]></Time>
<TimeTick>1632144581</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaEdit<br>Attached Text = Login<br>]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:41]]></Time>
<TimeTick>1632144581</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="56" status="Warning" nType="Description" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="381" nRep="55" status="Failed" nType="Run Error" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="49" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:41]]></Time>
<TimeTick>1632144581</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Login&quot; (of class JavaEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (77): &quot;			JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Login&quot;).Activate&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:41]]></Time>
<TimeTick>1632144581</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="58" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="76" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:48]]></Time>
<TimeTick>1632144588</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="60" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:50]]></Time>
<TimeTick>1632144590</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="61" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:50]]></Time>
<TimeTick>1632144590</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="63" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 14:29:55]]></Time>
<TimeTick>1632144595</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="65" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Enter PLU or IMEI.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5013742200473"]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:17]]></Time>
<TimeTick>1632144617</TimeTick>
<NodeArgs eType="Replay" icon="381" nRep="68" status="Warning" >
<Disp><![CDATA[Enter PLU or IMEI.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Enter PLU or IMEI]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Enter&nbsp;PLU&nbsp;or&nbsp;IMEI"&nbsp;(of&nbsp;class&nbsp;JavaEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:17]]></Time>
<TimeTick>1632144617</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Enter PLU or IMEI]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaEdit<br>Attached Text = Enter PLU or IMEI<br>]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:17]]></Time>
<TimeTick>1632144617</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="71" status="Warning" nType="Description" >
<Disp><![CDATA[Enter PLU or IMEI]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="381" nRep="70" status="Failed" nType="Run Error" >
<Disp><![CDATA[Enter PLU or IMEI]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="378" nRep="57" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:17]]></Time>
<TimeTick>1632144617</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Enter PLU or IMEI&quot; (of class JavaEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Banking\Automation\FunctionLibrary\Banking.qfl<BR/>Line (2490): &quot;JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Enter PLU or IMEI&quot;).Set intPLU&quot;.]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:17]]></Time>
<TimeTick>1632144617</TimeTick>
<NodeArgs eType="Replay" icon="380" nRep="73" status="Failed" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="2489" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Enter.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:19]]></Time>
<TimeTick>1632144619</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="75" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Enter.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:23]]></Time>
<TimeTick>1632144623</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="77" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:23]]></Time>
<TimeTick>1632144623</TimeTick>
<NodeArgs eType="Replay" icon="379" nRep="78" Source="C:\Banking\Automation\FunctionLibrary\Banking.qfl" SourceLine="-1" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 14:30:24]]></Time>
<TimeTick>1632144624</TimeTick>