<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R5"><DocLocation><![CDATA[C:\Banking\Automation\TestScripts\Testcase137_CH_294_05]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Testcase137_CH_294_05]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="432" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:20]]></Time>
<TimeTick>1632148820</TimeTick>
<NodeArgs eType="Replay" icon="435" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:20]]></Time>
<TimeTick>1632148820</TimeTick>
<NodeArgs eType="Replay" icon="435" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:25]]></Time>
<TimeTick>1632148825</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:25]]></Time>
<TimeTick>1632148825</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="12" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:27]]></Time>
<TimeTick>1632148827</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="14" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:27]]></Time>
<TimeTick>1632148827</TimeTick>
<NodeArgs eType="Replay" icon="438" nRep="16" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:27]]></Time>
<TimeTick>1632148827</TimeTick>
<NodeArgs eType="Replay" icon="438" nRep="18" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fc097abb195b0915582818a640b"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:27]]></Time>
<TimeTick>1632148827</TimeTick>
<NodeArgs eType="Replay" icon="438" nRep="20" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:27]]></Time>
<TimeTick>1632148827</TimeTick>
<NodeArgs eType="Replay" icon="438" nRep="22" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:27]]></Time>
<TimeTick>1632148827</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="23" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Override.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:27]]></Time>
<TimeTick>1632148827</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="25" >
<Disp><![CDATA[Override.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:29]]></Time>
<TimeTick>1632148829</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="26" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:29]]></Time>
<TimeTick>1632148829</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="28" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:32]]></Time>
<TimeTick>1632148832</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="29" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:32]]></Time>
<TimeTick>1632148832</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="31" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#6"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:33]]></Time>
<TimeTick>1632148833</TimeTick>
<NodeArgs eType="Replay" icon="439" nRep="33" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:35]]></Time>
<TimeTick>1632148835</TimeTick>
<NodeArgs eType="Replay" icon="439" nRep="35" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Manual Declare.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:43]]></Time>
<TimeTick>1632148843</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="37" >
<Disp><![CDATA[Manual Declare.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:52]]></Time>
<TimeTick>1632148852</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="39" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Declare Till / Mid-Day.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["CASH"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:54]]></Time>
<TimeTick>1632148854</TimeTick>
<NodeArgs eType="Replay" icon="439" nRep="41" >
<Disp><![CDATA[Declare Till / Mid-Day.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Enter Expected Quantity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["10.20"]]></Details>
<Time><![CDATA[9/20/2021 - 15:40:58]]></Time>
<TimeTick>1632148858</TimeTick>
<NodeArgs eType="Replay" icon="438" nRep="43" >
<Disp><![CDATA[Enter Expected Quantity.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Count Complete.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:41:02]]></Time>
<TimeTick>1632148862</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="45" >
<Disp><![CDATA[Count Complete.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[PIS Confirmation.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["919423"]]></Details>
<Time><![CDATA[9/20/2021 - 15:41:04]]></Time>
<TimeTick>1632148864</TimeTick>
<NodeArgs eType="Replay" icon="438" nRep="47" >
<Disp><![CDATA[PIS Confirmation.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 15:41:09]]></Time>
<TimeTick>1632148869</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="48" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:41:09]]></Time>
<TimeTick>1632148869</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="50" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="436" nRep="11" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Banking]]></Obj>
<Details ><![CDATA[Confirmation screen is displayed Successfully]]></Details>
<Time><![CDATA[9/20/2021 - 15:41:09]]></Time>
<TimeTick>1632148869</TimeTick>
<NodeArgs eType="User" icon="440" nRep="51" status="Passed" >
<Disp><![CDATA[Banking]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:47]]></Time>
<TimeTick>1632148967</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Save Print Output As]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:47]]></Time>
<TimeTick>1632148967</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Cancel.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:47]]></Time>
<TimeTick>1632148967</TimeTick>
<NodeArgs eType="Replay" icon="443" nRep="58" >
<Disp><![CDATA[Cancel.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="442" nRep="57" >
<Disp><![CDATA[Save Print Output As]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="441" nRep="56" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:49]]></Time>
<TimeTick>1632148969</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#7"]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:49]]></Time>
<TimeTick>1632148969</TimeTick>
<NodeArgs eType="Replay" icon="439" nRep="61" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:51]]></Time>
<TimeTick>1632148971</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="63" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:51]]></Time>
<TimeTick>1632148971</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="64" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:51]]></Time>
<TimeTick>1632148971</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="66" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Count Complete.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:42:55]]></Time>
<TimeTick>1632148975</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="68" >
<Disp><![CDATA[Count Complete.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:05]]></Time>
<TimeTick>1632148985</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="70" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="436" nRep="60" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:09]]></Time>
<TimeTick>1632148989</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Save Print Output As.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:09]]></Time>
<TimeTick>1632148989</TimeTick>
<NodeArgs eType="Replay" icon="442" nRep="73" >
<Disp><![CDATA[Save Print Output As.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="441" nRep="72" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:11]]></Time>
<TimeTick>1632148991</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:11]]></Time>
<TimeTick>1632148991</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="76" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:16]]></Time>
<TimeTick>1632148996</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="78" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:18]]></Time>
<TimeTick>1632148998</TimeTick>
<NodeArgs eType="Replay" icon="437" nRep="80" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Back Office Login(st).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:18]]></Time>
<TimeTick>1632148998</TimeTick>
<NodeArgs eType="Replay" icon="444" nRep="81" >
<Disp><![CDATA[Back Office Login(st).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="436" nRep="75" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Successfully logged out]]></Obj>
<Details ><![CDATA[Logged out successfully]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:18]]></Time>
<TimeTick>1632148998</TimeTick>
<NodeArgs eType="User" icon="440" nRep="82" status="Passed" >
<Disp><![CDATA[Successfully logged out]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/20/2021 - 15:43:18]]></Time>
<TimeTick>1632148998</TimeTick>
<NodeArgs eType="General" icon="445" nRep="83" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/20/2021 - 15:40:17" eTime="9/20/2021 - 15:43:18" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="434" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="433" nRep="6" status="Passed" >
<Disp><![CDATA[Testcase137_CH_294_05 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/20/2021 - 15:40:15" eTime="9/20/2021 - 15:43:18" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="431" nRep="3" status="Passed" >
<Disp><![CDATA[Test Testcase137_CH_294_05 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>