<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R5"><DocLocation><![CDATA[C:\Banking\Automation\TestScripts\Testcase76_CH_294_01]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Testcase76_CH_294_01]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="384" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:12]]></Time>
<TimeTick>1632150912</TimeTick>
<NodeArgs eType="Replay" icon="387" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:12]]></Time>
<TimeTick>1632150912</TimeTick>
<NodeArgs eType="Replay" icon="387" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:16]]></Time>
<TimeTick>1632150916</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:16]]></Time>
<TimeTick>1632150916</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="12" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:18]]></Time>
<TimeTick>1632150918</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="14" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:18]]></Time>
<TimeTick>1632150918</TimeTick>
<NodeArgs eType="Replay" icon="390" nRep="16" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:18]]></Time>
<TimeTick>1632150918</TimeTick>
<NodeArgs eType="Replay" icon="390" nRep="18" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fc097abb195b0915582818a640b"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:18]]></Time>
<TimeTick>1632150918</TimeTick>
<NodeArgs eType="Replay" icon="390" nRep="20" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:18]]></Time>
<TimeTick>1632150918</TimeTick>
<NodeArgs eType="Replay" icon="390" nRep="22" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:23]]></Time>
<TimeTick>1632150923</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="24" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:25]]></Time>
<TimeTick>1632150925</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="25" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:26]]></Time>
<TimeTick>1632150926</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="27" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:29]]></Time>
<TimeTick>1632150929</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="28" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:29]]></Time>
<TimeTick>1632150929</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="30" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#6"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:29]]></Time>
<TimeTick>1632150929</TimeTick>
<NodeArgs eType="Replay" icon="391" nRep="32" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:31]]></Time>
<TimeTick>1632150931</TimeTick>
<NodeArgs eType="Replay" icon="391" nRep="34" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Manual Declare.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:40]]></Time>
<TimeTick>1632150940</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="36" >
<Disp><![CDATA[Manual Declare.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:49]]></Time>
<TimeTick>1632150949</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="38" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Declare Till / Mid-Day.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["CASH"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:51]]></Time>
<TimeTick>1632150951</TimeTick>
<NodeArgs eType="Replay" icon="391" nRep="40" >
<Disp><![CDATA[Declare Till / Mid-Day.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Enter Expected Quantity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["20.34"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:55]]></Time>
<TimeTick>1632150955</TimeTick>
<NodeArgs eType="Replay" icon="390" nRep="42" >
<Disp><![CDATA[Enter Expected Quantity.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Count Complete.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:59]]></Time>
<TimeTick>1632150959</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="43" >
<Disp><![CDATA[Count Complete.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Count Complete.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:15:59]]></Time>
<TimeTick>1632150959</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="45" >
<Disp><![CDATA[Count Complete.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[PIS Confirmation.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["919123"]]></Details>
<Time><![CDATA[9/20/2021 - 16:16:03]]></Time>
<TimeTick>1632150963</TimeTick>
<NodeArgs eType="Replay" icon="390" nRep="47" >
<Disp><![CDATA[PIS Confirmation.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:16:08]]></Time>
<TimeTick>1632150968</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="48" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:16:08]]></Time>
<TimeTick>1632150968</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="50" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="388" nRep="11" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Banking]]></Obj>
<Details ><![CDATA[Confirmation screen is displayed Successfully]]></Details>
<Time><![CDATA[9/20/2021 - 16:16:08]]></Time>
<TimeTick>1632150968</TimeTick>
<NodeArgs eType="User" icon="392" nRep="51" status="Passed" >
<Disp><![CDATA[Banking]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:43]]></Time>
<TimeTick>1632151063</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Save Print Output As]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:43]]></Time>
<TimeTick>1632151063</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Cancel.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:43]]></Time>
<TimeTick>1632151063</TimeTick>
<NodeArgs eType="Replay" icon="395" nRep="58" >
<Disp><![CDATA[Cancel.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="394" nRep="57" >
<Disp><![CDATA[Save Print Output As]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="393" nRep="56" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:47]]></Time>
<TimeTick>1632151067</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Main Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#7"]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:47]]></Time>
<TimeTick>1632151067</TimeTick>
<NodeArgs eType="Replay" icon="391" nRep="61" >
<Disp><![CDATA[Main Menu.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:49]]></Time>
<TimeTick>1632151069</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="62" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:49]]></Time>
<TimeTick>1632151069</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="64" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:51]]></Time>
<TimeTick>1632151071</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="65" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:51]]></Time>
<TimeTick>1632151071</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="67" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Count Complete.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:17:56]]></Time>
<TimeTick>1632151076</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="69" >
<Disp><![CDATA[Count Complete.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:18:08]]></Time>
<TimeTick>1632151088</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="71" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="388" nRep="60" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Save Print Output As]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Cancel.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<NodeArgs eType="Replay" icon="395" nRep="78" >
<Disp><![CDATA[Cancel.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="394" nRep="77" >
<Disp><![CDATA[Save Print Output As]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="393" nRep="76" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="80" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="82" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="83" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:40]]></Time>
<TimeTick>1632151180</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="85" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:44]]></Time>
<TimeTick>1632151184</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="87" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:46]]></Time>
<TimeTick>1632151186</TimeTick>
<NodeArgs eType="Replay" icon="389" nRep="89" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Back Office Login(st).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:46]]></Time>
<TimeTick>1632151186</TimeTick>
<NodeArgs eType="Replay" icon="396" nRep="90" >
<Disp><![CDATA[Back Office Login(st).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="388" nRep="79" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Successfully logged out]]></Obj>
<Details ><![CDATA[Logged out successfully]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:46]]></Time>
<TimeTick>1632151186</TimeTick>
<NodeArgs eType="User" icon="392" nRep="91" status="Passed" >
<Disp><![CDATA[Successfully logged out]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/20/2021 - 16:19:46]]></Time>
<TimeTick>1632151186</TimeTick>
<NodeArgs eType="General" icon="397" nRep="92" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/20/2021 - 16:15:08" eTime="9/20/2021 - 16:19:46" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="386" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="385" nRep="6" status="Passed" >
<Disp><![CDATA[Testcase76_CH_294_01 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/20/2021 - 16:15:07" eTime="9/20/2021 - 16:19:46" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="383" nRep="3" status="Passed" >
<Disp><![CDATA[Test Testcase76_CH_294_01 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>